"""initial

Revision ID: d99f2e201631
Revises: 
Create Date: 2026-05-25 23:23:59.225969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99f2e201631'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('cognito_sub', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cognito_sub'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bottles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('distillery', sa.Text(), nullable=False),
    sa.Column('region', sa.Text(), nullable=False),
    sa.Column('bottle_type', sa.Text(), nullable=True),
    sa.Column('abv', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flavor_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name')
    )
    op.create_table('tasting_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bottle_id', sa.UUID(), nullable=False),
    sa.Column('tasted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('serving_style', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('situation', sa.Text(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('want_again', sa.Boolean(), nullable=True),
    sa.Column('f_smoky', sa.SmallInteger(), nullable=True),
    sa.Column('f_fruity', sa.SmallInteger(), nullable=True),
    sa.Column('f_floral', sa.SmallInteger(), nullable=True),
    sa.Column('f_spicy', sa.SmallInteger(), nullable=True),
    sa.Column('f_woody', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bottle_id'], ['bottles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_flavor_tags',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['tasting_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['flavor_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_flavor_tags')
    op.drop_table('tasting_sessions')
    op.drop_table('flavor_tags')
    op.drop_table('bottles')
    op.drop_table('users')
    # ### end Alembic commands ###
